spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hitman007IN/Microservices_NetflixOSS_Kafka_Demo
          search-paths:
            - "ms-config-properties/{application}/{profile}"