spring:
  profiles:
    active: native
---

spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:///Users/vishakhrameshan/Documents/Workspace/microservice_netflixOSS_kafka/ms-config-properties/{application}/{profile},
            file:///Users/vishakhrameshan/Documents/Workspace/microservice_netflixOSS_kafka/ms-config-properties/global/{application}